# -*- coding: utf-8 -*-
"""EDA_Project_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xs-g2eGA4CEQUD4EvhLtCRiiUTeEnnTg

# **Title of the Project**
# **Tech Layoffs and Hiring Trends Analysis**

# **Problem Statement**
- The technology industry experiences frequent changes in hiring and layoffs due to market conditions,
company performance, and economic factors. This project aims to analyze tech layoffs and hiring
trends to understand patterns, affected industries, and workforce changes.

# **Objective:**
• To analyze trends in tech layoffs and hiring.  
• To identify companies with the highest layoffs.  
• To study hiring patterns across different years and industries.  
• To understand the impact of layoffs on the tech workforce.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/tech_layoffs_hiring_trends_0.csv')
df.shape

# Checking the Dataset which columns are present
df.columns

# Numerical Columns
num_cols=df.select_dtypes(include=['int64','float64']).columns
num_cols

# Categorical Columns
cat_cols=df.select_dtypes(include=['object']).columns
cat_cols

# Information about the entire dataframe
df.info()

df.dtypes

# Understanding the entire dataframe
df.head()

"""# **Observation:**
- Real Numerical Columns:
1. layoffs_count
2. open_roles

# - **Discrete Numerical Columns:**
1. year
2. layoff_percentage
3. ai_automation_impact    
4. ai_replacement_risk
5. remote_jobs_percentage
6. stock_growth_percent    
7. revenue_growth_percent  
8. salary_budget_change   
9. ai_adoption_level       
10. employee_sentiment    
11. job_security_score

# - **Categorical Columns:**
1. record_id             
2. company_name           
3. industry                 
4. country                  
5. company_size            
6. month  
7. reason_for_layoffs
8. hiring_trend
9. top_hiring_role
10. market_condition       
"""

# Check whether Null Values Present or Not
df.isnull().sum()

"""# **Observation:**
- There are so many null values in the Dataset.
"""

# Calculate the percentage of null values
(df.isnull().sum()/len(df))*100

# Filling the Null Values in Real Numerical column with either mean or median
cols=['layoffs_count','open_roles']
for col in cols:
  df[col]=df[col].fillna(df[col].mean())

# # Filling the Null Values in Discrete Numerical column or Categorical column with mode
cols=['company_name','industry','country','company_size',
      'layoff_percentage','reason_for_layoffs','ai_automation_impact',
      'ai_replacement_risk','hiring_trend','remote_jobs_percentage',
      'top_hiring_role','stock_growth_percent','revenue_growth_percent',
      'salary_budget_change','ai_adoption_level','employee_sentiment',
      'job_security_score','market_condition'
      ]

for col in cols:
  df[col]=df[col].fillna(df[col].mode()[0])

df.isnull().sum()

# Check the Duplicates Present or not
df.duplicated().sum()

"""# **Observation:**
- There is no duplicate values in dataset.
"""

df.describe()

sns.histplot(df,x='layoffs_count',
             bins=3,
             stat='probability',
             palette='tab10',
             color='green',
             kde=True)
plt.title('Distribution of Layoffs in a Company')
plt.show()

sns.histplot(df,x='open_roles',
             bins=3,
             stat='probability',
             palette='tab10',
             color='green',
             kde=True)
plt.title('Distribution of Roles in a Company')
plt.show()

a=df['industry'].value_counts()
plt.pie(a.values,
        labels=a.index,autopct='%0.2f%%')
plt.title('Industry')
plt.show()

a=df['reason_for_layoffs'].value_counts()
plt.pie(a.values,
        labels=a.index,autopct='%0.2f%%')
plt.title('Reasons For Layoofs in a Company')
plt.show()

a=df['market_condition'].value_counts()
plt.pie(a.values,
        labels=a.index,autopct='%0.2f%%')
plt.title('Market_Condition')
plt.show()

# Which companies had the highest number of layoffs?
df.groupby('company_name')['layoffs_count'].count().sort_values(ascending=False)

# Visualization for Company name and layoffs columns
plt.figure(figsize=(22,6))
ax=sns.barplot(df,x='company_name',y='layoffs_count',palette='hls')
plt.xticks(rotation=90)
for i in ax.containers:
    ax.bar_label(i)
plt.title('Company Name vs Layoffs Count')
plt.show()

"""# **Observation:**
- OpenAI recorded the highest layoff count (983), significantly higher than all other companies in the dataset.

- Spotify (622), Databricks (619), and Google (616) follow OpenAI, but there is a noticeable gap between OpenAI and the rest.

- Most of the top companies have layoff counts ranging between 550 and 620, indicating a relatively similar level of workforce reduction among leading firms.
"""

# Which year recorded the most layoffs?
df.groupby('year')['layoffs_count'].count().sort_values(ascending=False)

sns.scatterplot(df,x='year',y='layoffs_count')
plt.title('Most Layoffs in which year')
plt.show()

"""# **Observation:**
- 2024 recorded the highest number of layoffs (4,019) among the three years.

- 2026 followed closely with 4,004 layoffs, only 15 fewer - than 2024.

- 2025 had the lowest layoff count (3,977), but the difference from the highest year is only 42 layoffs.

- The layoff counts are fairly consistent across all three years, indicating a stable trend rather than significant fluctuations.
"""

# Which industries were most affected by layoffs?
df.groupby('industry')['layoffs_count'].count().sort_values(ascending=False)

plt.figure(figsize=(22,6))
ax=sns.barplot(df,x='industry',y='layoffs_count',palette='hls')
plt.xticks(rotation=90)
for i in ax.containers:
    ax.bar_label(i)
plt.title('In which Industry has most Layoffs')
plt.show()

"""# **Observation:**
- The Social Media industry recorded the highest layoff count (2,158), far exceeding other sectors.

- While E-Commerce, Cloud, Cybersecurity, Gaming, AI, and FinTech all experienced significant layoffs, their counts were relatively close, ranging from 1,617 to 1,665.

- This suggests that workforce reductions were widespread across the technology ecosystem, with Social Media being the most affected industry."
"""

# Which companies continued hiring despite layoffs?
df['hiring_trend'].value_counts()

a=df['hiring_trend'].value_counts()
plt.pie(a.values,
        labels=a.index,autopct='%0.2f%%')
plt.title('Despite Layoofs In Hiring Trend')
plt.show()

"""# **Observation:**
- Hiring Freeze emerged as the dominant hiring trend (5,280), followed by Moderate Hiring (4,568).

-  In contrast, Aggressive Hiring was relatively rare (495), suggesting that most organizations adopted a cautious approach to recruitment, with many either slowing hiring activities or maintaining existing workforce levels."
"""

# What is the trend of hiring vs layoffs over time?
df.groupby('year')[['hiring_trend','layoffs_count']].sum()

"""# **Observation:**
- Total layoffs remained consistently high between 2024 and 2026.

-  The highest layoff volume was observed in 2024 (20.22 million), followed by 2026 (19.96 million), while 2025 recorded the lowest total (19.81 million).

-  The relatively small variation across years indicates a sustained trend of workforce reductions rather than a one-time event."
"""

# Which locations experienced the highest layoffs?
df.groupby('country')['layoffs_count'].count().sort_values(ascending=False)

plt.figure(figsize=(22,6))
ax=sns.barplot(df,x='country',y='layoffs_count',palette='hls')
plt.xticks(rotation=90)
for i in ax.containers:
    ax.bar_label(i)
plt.title('In which Country has most Layoffs')
plt.show()

"""# **Observation:**
- The UK experienced the highest layoff count (2,348), significantly exceeding other countries.

- Singapore, the USA, India, Canada, and Germany reported similar layoff levels, ranging from 1,908 to 1,970.

- This indicates that while layoffs were a global phenomenon, the UK was the most affected country in the dataset."
"""

# How does the distribution of market conditions vary across different companies?
plt.figure(figsize=(12,6))
sns.countplot(df,x='company_name',hue='market_condition',palette='tab10',)
plt.xticks(rotation=90)
plt.show()

# How do hiring trends vary across different companies?
plt.figure(figsize=(12,6))
sns.countplot(df,x='company_name',hue='hiring_trend',palette='cubehelix',)
plt.xticks(rotation=90)
plt.show()

# How do hiring trends vary across different industries?
plt.figure(figsize=(12,6))
sns.countplot(df,x='industry',hue='hiring_trend',palette='tab10')
plt.xticks(rotation=90)
plt.show()

# How do hiring trends differ across company sizes?
plt.figure(figsize=(12,6))
sns.countplot(df,x='company_size',hue='hiring_trend',palette='cubehelix',)
plt.xticks(rotation=90)
plt.show()

# How do reasons for layoffs vary across different company sizes?
plt.figure(figsize=(12,6))
sns.countplot(df,x='company_size',hue='reason_for_layoffs',palette='husl',)
plt.xticks(rotation=90)
plt.show()

# Which industry has the highest number of layoffs for each reason?
plt.figure(figsize=(12,6))
sns.countplot(df,x='industry',hue='reason_for_layoffs',palette='mako')
plt.xticks(rotation=90)
plt.show()

# How do top hiring roles vary across different company sizes?
sns.countplot(df,x='company_size',hue='top_hiring_role',palette='YlOrBr')
plt.title('Top Hiring roles in a Company')
plt.show()

# Which country has the highest number of layoffs for each layoff reason?
plt.figure(figsize=(12,6))
sns.countplot(df,x='country',hue='reason_for_layoffs',palette='rocket',)
plt.xticks(rotation=90)
plt.show()

# Are startups or large companies more affected?
df['company_size'].value_counts()

# Which company size category is most affected by layoffs?
a=df['company_size'].value_counts()
plt.pie(a.values,
        labels=a.index,autopct='%0.2f%%')
plt.title('More Companies are Affected')
plt.show()

"""# **Observation:**
- Big Tech companies accounted for the largest proportion of records (3,414), while Mid-size, Enterprise, and Startup companies were represented almost equally, with counts close to 2,850–2,870.

- This indicates a well-balanced dataset with a slight concentration toward large technology firms."
"""

# How many layoff events occurred for each company across different layoff reason
pivot=pd.pivot_table(df,columns='reason_for_layoffs',
               index='company_name',
               values='layoffs_count',
               aggfunc='count',
               margins=True)
pivot

"""# **Observation:**
- Overhiring Correction is the leading reason for layoffs, accounting for 3,026 cases (25.2%), making it the most significant driver of workforce reductions.

- The other reasons—AI Automation (2,272), Cost Cutting (2,233), Market Slowdown (2,205), and Restructuring (2,264)—are relatively balanced, each contributing around 18–19% of total layoffs.

- This suggests that layoffs were driven by a combination of strategic and economic factors, with overexpansion during previous hiring cycles being the primary cause.
"""

# What are the most in-demand roles among hiring companies?
df['top_hiring_role'].value_counts()

a=df['top_hiring_role'].value_counts()
plt.pie(a.values,
        labels=a.index,autopct='%0.2f%%')
plt.title('Top Hiring Roles')
plt.show()

"""# **Observation:**
- "ML Engineer (2,686) and Data Scientist (2,016) emerged as the most sought-after roles, demonstrating the growing focus on artificial intelligence and data analytics.

- Traditional technology roles such as Frontend Developer, DevOps Engineer, Software Engineer, and Cloud Engineer also maintained strong demand, while Cybersecurity Analysts and Product Managers continued to play critical roles in organizational growth and digital transformation."
"""

# Which company size has the highest overall job security score in each country?
pd.pivot_table(df,columns='country',
               index='company_size',
               values='job_security_score',
               aggfunc='sum',
               margins=True)

pivot = pd.pivot_table(
    df,
    columns='country',
    index='company_size',
    values='job_security_score',
    aggfunc='sum'
)

pivot.plot(
    kind='bar',
    figsize=(12,6)
)

plt.title('Country-wise Job Security Score by Company Size')
plt.ylabel('Total Job Security Score')
plt.xticks(rotation=0)
plt.show()

"""# **Observation:**
- The UK emerged as the leading country across all company-size categories, recording the highest overall total (13,457.3).

- Big Tech companies accounted for the largest contribution (19,894.0), surpassing Enterprise, Mid-size, and Startup organizations.

-  While Singapore and the USA also showed substantial activity, the UK consistently dominated across every company-size segment, indicating a stronger concentration of workforce-related changes in that market."
"""

# Which layoff reasons are most common during different market conditions?
pd.pivot_table(df,columns='reason_for_layoffs',
               index='market_condition',
               values='layoffs_count',
               aggfunc='count',
               margins=True)

pivot = pd.pivot_table(
    df,
    columns='reason_for_layoffs',
    index='market_condition',
    values='layoffs_count',
    aggfunc='count'
)

plt.figure(figsize=(12,6))
sns.heatmap(pivot, annot=True, fmt='.0f', cmap='YlOrRd')
plt.title('Layoff Reasons Across Market Conditions')
plt.show()

"""# **Observation:**
- "Stable market conditions accounted for the highest number of layoffs (4,387), followed by Bull Market (3,864) and Recession (3,749).

- Across all market environments, Overhiring Correction emerged as the primary reason for layoffs, highlighting companies' efforts to realign workforce sizes after aggressive hiring periods.

-  The findings suggest that organizational restructuring and workforce optimization occur regardless of broader economic conditions."
"""

# How does AI replacement risk vary across companies of different sizes?
pd.pivot_table(df,columns='company_size',
               index='company_name',
               values='ai_replacement_risk',
               aggfunc='sum',
               margins=True)

pivot = pd.pivot_table(
    df,
    columns='company_size',
    index='company_name',
    values='ai_replacement_risk',
    aggfunc='sum'
)

pivot.plot(kind='bar', figsize=(15,6))

plt.title('AI Replacement Risk Across Companies')
plt.ylabel('Total AI Replacement Risk')
plt.xticks(rotation=90)
plt.show()

"""# **Observation:**
- Big Tech companies recorded the highest overall value (25,153.9), significantly exceeding Enterprise (21,089.4), Mid-size (21,060.2), and Startup (21,206.5) companies.

- The totals for Enterprise, Mid-size, and Startup companies are very close, indicating a balanced distribution among these categories.

- Big Tech contributed nearly 28.4% of the overall total (88,510.0), making it the dominant company-size segment.

"""

# Which hiring role is most common across all company sizes?
pd.crosstab(df['company_size'],df['top_hiring_role'],margins=True)

ct = pd.crosstab(
    df['company_size'],
    df['top_hiring_role']
)

ct.plot(kind='bar', figsize=(12,6))

plt.title('Top Hiring Roles Across Company Sizes')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.show()

"""# **Observation:**
- ML Engineer is the most demanded role across all company sizes, with 2,686 hires, highlighting the growing focus on AI and machine learning.

- Data Scientist (2,016) is the second most sought-after role, reinforcing the importance of data-driven decision-making.

- Cybersecurity Analyst (1,171) has the lowest total hiring count among the listed roles, though demand remains substantial.
"""

# Correlation Analysis
num_cols=df.select_dtypes(include=['int64','float64'])
plt.figure(figsize=(14,8))
sns.heatmap(num_cols.corr(),annot=True,cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""# **Possible Outcomes from the Analysis:**

1. AI Skills Will Dominate Hiring
  - ML Engineers and Data Scientists are the most demanded roles, indicating continued growth in AI, Machine Learning, and Analytics careers.

2. Overhiring Corrections May Continue
  - Since Overhiring Correction is the leading reason for layoffs, companies may continue optimizing workforce sizes rather than aggressively expanding.

3. Big Tech Will Remain the Key Driver
  - Big Tech companies show both the highest hiring and workforce activity, meaning they will continue to influence overall industry employment trends.

4. Demand for Cloud and Cybersecurity Will Stay Strong
  - Cloud Engineers and Cybersecurity Analysts remain among the top hiring roles, reflecting increased focus on cloud infrastructure and security.

5. Organizations Will Adopt a Cautious Hiring Approach
  - Hiring Freeze and Moderate Hiring are more common than Aggressive Hiring, suggesting companies will prioritize controlled growth.

6. AI Automation May Reshape Jobs
  - AI Automation is a major reason for layoffs, which could reduce demand for repetitive tasks while increasing demand for AI-related skills.

7. Global Workforce Restructuring Will Continue
  - Similar layoff counts across countries and years indicate that workforce restructuring is a widespread and ongoing trend.

8. Data and Analytics Careers Have Strong Future Prospects
  - High demand for Data Scientists and ML Engineers suggests strong career opportunities for professionals with Python, SQL, Machine Learning, and Data Analytics skills.

# **Executive Conclusion:**

- The overall trend suggests that companies are reducing excess workforce through restructuring and overhiring corrections while simultaneously increasing investments in AI, Machine Learning, Data Science, Cloud Computing, and Cybersecurity. Professionals with AI and data-related skills are likely to have the strongest career opportunities in the coming years.
"""